# Generated by Django 4.2.16 on 2024-11-28 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('birthday', '0002_auto_20241127_0043'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='birthday',
            options={'verbose_name': 'Запись о ДР', 'verbose_name_plural': 'Записи о ДР'},
        ),
        migrations.AddField(
            model_name='birthday',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор записи'),
        ),
    ]
